server:
  port: 8080
spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
      uri: mongodb://rranjan:rranjan01@mongodb:27017/sampledb # For openshift
#      uri: mongodb://localhost:27017/db_example
#      uri: mongodb://mymongo:27017/db_example    # Commented for openshift
#      grid-fs-database: images
logging:
  level:
    org.springframework.web: DEBUG
